version: 0.2

phases:
    install:
        runtime-versions:
            docker: 18
artifacts:
    type: zip
    files:
        - 'client/**/*'
        - 'server/**/*'
        - 'nginx/**/*'
        - Dockerrun.aws.json