version: "3.8"

services:
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 8082:8082

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"

  nginx: 
    container_name: nginx
    depends_on: 
      - client
      - server
    ports: 
      - "80:80"
    build:
      context: ./nginx

  vredis:
    container_name: vredis
    image: redis:latest
    ports:
      - 6329:6329
