version: '2.4'

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "8081:8081"
      - "9229:9229"
    volumes:
      - .:/app
  mongo:
      image: mongo
      volumes:
        - ./mongodb/data/db
      ports:
        - '27017:27017'