version: "3.8"

services:
  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 82:82
    depends_on:
      - "iredis"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "8081:8081"

  iredis:
    container_name: iredis
    image: redis:latest
    ports:
      - 6329:6329
