version: '3.8'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "8082:8082"
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "80:3000"
  redis:
    image: redis:latest
    ports:
      - 6329:6329
