version: "3.8"

services:
  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 8082:8082
    depends_on:
      - "vredis"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "80:3000"

  vredis:
    container_name: vredis
    image: redis:latest
    ports:
      - 6328:6329
